[tool.poetry]
name = "codac_tool"
version = "0.9.0"
description = "Simple tool that takes two comma-separated datasets, joins them and filters by countries"
authors = ["Kacper Wandel <kacperwandel@gmail.com>"]
