name: Run tests & build

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest 

  build:
    name: build
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Build wheel
        run: poetry build

      - name: Configure Git
        run: |
          git config --global user.email "kacperwandel@gmail.com"
          git config --global user.name "darkkavon"
          
      - name: Commit and push wheel
        run: |
          git add -f ./dist/*.whl
          git add .
          git commit -m 'Pushing a new wheel'
          git push