name: Run tests & build

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  runs-on: ubuntu-latest
  test:
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest 

  build:
    needs: test
    steps:
      - name: Install requirements
              run: pip install -r requirements.txt

      - name: Build wheel
        run: poetry build